[build]
builder = "nixpacks"
buildCommand = "prisma generate && next build"

[deploy]
startCommand = "npx prisma db push --accept-data-loss && npx prisma db seed && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
